# Proveedor AWS
provider "aws" {
  region = "us-east-2" # Changed to us-east-2 to match Packer configs
}

module "network" {
  source              = "./modules/network"
  vpc_name            = "MEAN_vpc"
  vpc_cidr            = "10.0.0.0/16"
  public_subnets = {
    "public_subnet_1" = 1
    "public_subnet_2" = 2
    "public_subnet_3" = 3
  }
  gateway             = module.igw.gateway
  private_subnet_cidr = "10.0.0.0/24"
  private_subnet_az   = "us-east-2a" # Ensure this AZ is valid for us-east-2, or adjust if needed
  private_subnet_name = "MEAN_private_subnet"
}

module "igw" {
  source = "./modules/igw"
  vpc_id = module.network.vpc_id
}

module "security" {
  source     = "./modules/security"
  vpc_id     = module.network.vpc_id
  web_server = "MEAN_web_server"
  # Add outputs for web_sg_id and mongo_sg_id if they are defined in modules/security/outputs.tf
}

module "llave" {
  source = "./modules/llave"
  name   = "MEAN_key"
}

module "ami" {
  source = "./modules/ami"
  # No inputs needed here, as the Packer templates are hardcoded relative paths within the module itself
}

module "servidores" {
  source = "./modules/servidores"

  # Pass the AMI IDs generated by the 'ami' module
  ean_ami_id     = module.ami.ean_ami_id
  mongodb_ami_id = module.ami.mongodb_ami_id

  # Map other variables to their respective module outputs or explicit values
  public_subnet_1            = module.network.public_subnet_1
  ssh_private_key            = module.llave.ssh_private_key # Make sure this output is correctly named in module.llave
  key_name                   = module.llave.key_pair_name # Assuming module.llave exports key_pair_name
  web_server_count           = 1
  web_server_subnet_id_1     = module.network.public_subnet_1 # Use consistent subnet IDs as defined in modules/servidores/main.tf
  web_server_subnet_id_2     = module.network.public_subnet_2 # Use consistent subnet IDs as defined in modules/servidores/main.tf
  web_server_private_ip_base = "10.0.101" # This variable is used for ENI private_ips
  mongodb_subnet_id          = module.network.private_subnet_id # Make sure this output is defined in module.network
  mongodb_private_ip         = "10.0.0.40"
  webserver_1_private_ip     = "10.0.101.30"
  webserver_2_private_ip     = "10.0.102.30"
  mongodb_security_group_id  = module.security.mongodb_security_group_id # Make sure this output is defined in module.security
  security_group_ids         = module.security.web_server_security_group_id # Make sure this output is defined in module.security
}

module "load_balancer" {
  source            = "./modules/load_balancer"
  lb_name           = "app-load-balancer"
  security_groups   = [module.security.web_server_security_group_id]
  subnets           = [module.network.public_subnet_1, module.network.public_subnet_2]
  vpc_id            = module.network.vpc_id
  instance_target_count = 2
  target_ids        = module.servidores.web_server_ids # This output should be correct from modules/servidores/outputs.tf
}